import type { Metadata } from "next";
import "./globals.css";
// import { Roboto } from "next/font/google";

import localFont from "next/font/local";
const roboto = localFont({
	src: [
		{ path: "../font/static/Roboto-Regular.ttf", weight: "100" },
		// {
		// 	path: "../font/static/Roboto-Medium.ttf",
		// 	weight: "500",
		// },
	],
	display: "swap",
	variable: "--font-roboto",
});

// const roboto = Roboto({
// 	subsets: ["latin"],
// 	weight: ["400", "500", "700"],
// 	style: ["normal", "italic"],
// 	variable: "--font-roboto",
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.className}`}>{children}</body>
		</html>
	);
}
