import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "sonner";
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";
import SlideSession from "@/components/slide-session";
import accountApiRequest from "@/apiRequest/account";
import { handleErrorApi } from "@/lib/utils";
import { AccountResType } from "@/schemaValidations/account.schema";

const inter = Inter({
	subsets: ["vietnamese"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const sessionToken = cookieStore.get("sessionToken")?.value;
	let user = null;
	try {
		if (sessionToken) {
			const data = await accountApiRequest.me(sessionToken);
			user = data.payload.data;
			console.log(user);
		}
	} catch (error) {
		handleErrorApi({ error });
	}
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.className}`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<AppProvider
						initialSessionToken={sessionToken}
						user={user as AccountResType["data"]}
					>
						<Header user={user as AccountResType["data"]} />
						{children}
						<Toaster />
						<SlideSession />
					</AppProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
