import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { ThemeProvider } from "./theme-provider";
import { AppProvider } from "./AppProvider";
import { cookies } from "next/headers";

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["400", "500", "700"],
	style: ["normal", "italic"],
	variable: "--font-roboto",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const sessionToken = cookieStore.get("sessionToken")?.value;
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${roboto.className}`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<AppProvider initSessionToken={sessionToken}>{children}</AppProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
